variable region {}
variable project_name {}
variable vpc_cidr {}
variable subnet_cidr_public_1 {}
variable subnet_cidr_public_2 {}
variable subnet_cidr_private_1 {}
variable subnet_cidr_private_2 {}
variable alb_port {}
variable frontend_port {}
variable backend_port {}
variable db_port {}
variable subnet_cidr_private_3 {}
variable subnet_cidr_private_4 {}
variable db_username {}
variable db_password {}
