variable project_name {}
variable alb_sg_id {}
variable public_subnet_1_id {}
variable public_subnet_2_id {}
variable vpc_id {}
variable ecs_sg_backend_id {}
variable backend_port {}
variable private_subnet_1_id {}
variable private_subnet_2_id {}
