name: Deploy a three tier application to AWS ECS Fargate using GitHub Actions
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      BACKEND_ECR_URI: 

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
      
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # Initialize Terraform and apply the configuration
      - name: Creating infrastructure with Terraform
        run: |
          echo "Creating infrastructure with Terraform..."
          cd terraform
          cd prod
          terraform init
          terraform plan -var-file="values.tfvars"
          terraform apply -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      # Retrieve ECR repository URIs from Terraform output
      - name: Retrieve ECR repository URIs
        id: ecr-uris
        run: |
          echo "ECR_BACKEND_URI=$(terraform output -raw backend_repository_url)" >> $GITHUB_ENV
          echo "ECR_FRONTEND_URI=$(terraform output -raw frontend_repository_url)" >> $GITHUB_ENV

      # Get ECS Cluster and service information
      - name: Get ECS Cluster and service information
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "BACKEND_SERVICE_NAME=$(terraform output -raw backend_service_name)" >> $GITHUB_ENV
          echo "FRONTEND_SERVICE_NAME=$(terraform output -raw frontend_service_name)" >> $GITHUB_ENV

      # Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com


      # Build and push Docker images for backend
      - name: Build and push backend
        run: |
          docker build -t notestack-backend ./note-stack-app/backend
          docker tag notestack-backend:latest $ECR_BACKEND_URI:latest
          docker push $ECR_BACKEND_URI:latest

      # Build and push Docker images for frontend
      - name: Build and push frontend
        run: |
          docker build -t notestack-frontend ./note-stack-app/frontend
          docker tag notestack-frontend:latest $ECR_FRONTEND_URI:latest
          docker push $ECR_FRONTEND_URI:latest 


      # Update ECS services to use backend image
      - name: Update ECS services with the backend image
        run: |
          aws ecs update-service \
          --cluster ${{ env.CLUSTER_NAME }} \
          --service ${{ env.BACKEND_SERVICE_NAME }} \
          --force-new-deployment \
          --region eu-central-1


      # Update ECS services to use frontend image
      - name: Update ECS services with the frontend image
        run: |
          aws ecs update-service \
          --cluster ${{ env.CLUSTER_NAME }} \
          --service ${{ env.FRONTEND_SERVICE_NAME }} \
          --force-new-deployment \
          --region eu-central-1

     # Wait for the backend services to stabilize
      - name: Wait for services to stabilize
        run: |
          aws ecs wait services-stable \
          --cluster ${{ env.CLUSTER_NAME }} \
          --services ${{ env.BACKEND_SERVICE_NAME }} \
          --region eu-central-1

      # Wait for the frontend services to stabilize
      - name: Wait for frontend services to stabilize
        run: |  
          aws ecs wait services-stable \
          --cluster ${{ env.CLUSTER_NAME }} \
          --services ${{ env.FRONTEND_SERVICE_NAME }} \
          --region eu-central-1





